// 添加
const PUSH_COMP = 'PUSH_COMP';
// 删除
const DEL_COMP = 'DEL_COMP';
// 设置激活组件
const SET_ACTIVECOMP = 'SET_ACTIVECOMP';
// 暂存组件数据
const STORAGE_COMPONENTLIST = 'STORAGE_COMPONENTLIST';

// 添加多页面支持
const SET_ACTIVEPAGEINDEX = 'SET_ACTIVEPAGEINDEX';
const ADD_PAGE = 'ADD_PAGE';
const PUSH_PAGE_COMP = 'PUSH_PAGE_COMP'
const STORAGE_PAGE_DATA = 'STORAGE_PAGE_DATA';
const DEL_PAGE = 'DEL_PAGE';
export {
    PUSH_COMP,
    DEL_COMP,
    SET_ACTIVECOMP,
    STORAGE_COMPONENTLIST,
    SET_ACTIVEPAGEINDEX,
    ADD_PAGE,
    PUSH_PAGE_COMP,
    STORAGE_PAGE_DATA,
    DEL_PAGE
}